export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_SERVER = 'INTERNAL_SERVER',
  INVALID_REQUEST = 'INVALID_REQUEST',
  DATABASE_DOWN = 'DATABASE_DOWN',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
}